version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: root
      DB_PASS: mypassword
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
